/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DashboardLayoutRouteImport } from './routes/_dashboardLayout'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LoginIndexRouteImport } from './routes/login/index'
import { Route as DashboardLayoutPortfolioIndexRouteImport } from './routes/_dashboardLayout/portfolio/index'
import { Route as DashboardLayoutPortfolioAddIndexRouteImport } from './routes/_dashboardLayout/portfolio/add/index'
import { Route as DashboardLayoutPortfolioEditIdRouteImport } from './routes/_dashboardLayout/portfolio/edit/$id'

const DashboardLayoutRoute = DashboardLayoutRouteImport.update({
  id: '/_dashboardLayout',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginIndexRoute = LoginIndexRouteImport.update({
  id: '/login/',
  path: '/login/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardLayoutPortfolioIndexRoute =
  DashboardLayoutPortfolioIndexRouteImport.update({
    id: '/portfolio/',
    path: '/portfolio/',
    getParentRoute: () => DashboardLayoutRoute,
  } as any)
const DashboardLayoutPortfolioAddIndexRoute =
  DashboardLayoutPortfolioAddIndexRouteImport.update({
    id: '/portfolio/add/',
    path: '/portfolio/add/',
    getParentRoute: () => DashboardLayoutRoute,
  } as any)
const DashboardLayoutPortfolioEditIdRoute =
  DashboardLayoutPortfolioEditIdRouteImport.update({
    id: '/portfolio/edit/$id',
    path: '/portfolio/edit/$id',
    getParentRoute: () => DashboardLayoutRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginIndexRoute
  '/portfolio': typeof DashboardLayoutPortfolioIndexRoute
  '/portfolio/edit/$id': typeof DashboardLayoutPortfolioEditIdRoute
  '/portfolio/add': typeof DashboardLayoutPortfolioAddIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginIndexRoute
  '/portfolio': typeof DashboardLayoutPortfolioIndexRoute
  '/portfolio/edit/$id': typeof DashboardLayoutPortfolioEditIdRoute
  '/portfolio/add': typeof DashboardLayoutPortfolioAddIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_dashboardLayout': typeof DashboardLayoutRouteWithChildren
  '/login/': typeof LoginIndexRoute
  '/_dashboardLayout/portfolio/': typeof DashboardLayoutPortfolioIndexRoute
  '/_dashboardLayout/portfolio/edit/$id': typeof DashboardLayoutPortfolioEditIdRoute
  '/_dashboardLayout/portfolio/add/': typeof DashboardLayoutPortfolioAddIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/portfolio'
    | '/portfolio/edit/$id'
    | '/portfolio/add'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/login' | '/portfolio' | '/portfolio/edit/$id' | '/portfolio/add'
  id:
    | '__root__'
    | '/'
    | '/_dashboardLayout'
    | '/login/'
    | '/_dashboardLayout/portfolio/'
    | '/_dashboardLayout/portfolio/edit/$id'
    | '/_dashboardLayout/portfolio/add/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardLayoutRoute: typeof DashboardLayoutRouteWithChildren
  LoginIndexRoute: typeof LoginIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_dashboardLayout': {
      id: '/_dashboardLayout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof DashboardLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login/': {
      id: '/login/'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_dashboardLayout/portfolio/': {
      id: '/_dashboardLayout/portfolio/'
      path: '/portfolio'
      fullPath: '/portfolio'
      preLoaderRoute: typeof DashboardLayoutPortfolioIndexRouteImport
      parentRoute: typeof DashboardLayoutRoute
    }
    '/_dashboardLayout/portfolio/add/': {
      id: '/_dashboardLayout/portfolio/add/'
      path: '/portfolio/add'
      fullPath: '/portfolio/add'
      preLoaderRoute: typeof DashboardLayoutPortfolioAddIndexRouteImport
      parentRoute: typeof DashboardLayoutRoute
    }
    '/_dashboardLayout/portfolio/edit/$id': {
      id: '/_dashboardLayout/portfolio/edit/$id'
      path: '/portfolio/edit/$id'
      fullPath: '/portfolio/edit/$id'
      preLoaderRoute: typeof DashboardLayoutPortfolioEditIdRouteImport
      parentRoute: typeof DashboardLayoutRoute
    }
  }
}

interface DashboardLayoutRouteChildren {
  DashboardLayoutPortfolioIndexRoute: typeof DashboardLayoutPortfolioIndexRoute
  DashboardLayoutPortfolioEditIdRoute: typeof DashboardLayoutPortfolioEditIdRoute
  DashboardLayoutPortfolioAddIndexRoute: typeof DashboardLayoutPortfolioAddIndexRoute
}

const DashboardLayoutRouteChildren: DashboardLayoutRouteChildren = {
  DashboardLayoutPortfolioIndexRoute: DashboardLayoutPortfolioIndexRoute,
  DashboardLayoutPortfolioEditIdRoute: DashboardLayoutPortfolioEditIdRoute,
  DashboardLayoutPortfolioAddIndexRoute: DashboardLayoutPortfolioAddIndexRoute,
}

const DashboardLayoutRouteWithChildren = DashboardLayoutRoute._addFileChildren(
  DashboardLayoutRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardLayoutRoute: DashboardLayoutRouteWithChildren,
  LoginIndexRoute: LoginIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
